### ISSUE TITLE
How to run cmdline?

### ISSUE THREAD

**Issue by distributev** [distributev/mailmerger#12]
I tried various combination of arguments and could not get it running. Please let me know the correct arguments I need to pass to get it running. Below you see an example of what it was tried.

![image](https://user-images.githubusercontent.com/19224635/39619226-5d2e4942-4f87-11e8-912b-ad08c34ae19f.png)

**Comment by p-bye** [comment]
Will depend on where the template file is located in relation to the configuration.  The following works for me....
![run_configurations](https://user-images.githubusercontent.com/38662460/39620024-add96a30-4f81-11e8-8283-95dbc4d00555.png)

This will keep everything within the examples folder.  e.g. generated logs & outputfolder.
