### ISSUE TITLE
Sample of run configuration to execute server from Eclipse?

### ISSUE THREAD

**Issue by distributev** [distributev/mailmerger#13]
Related with the issue https://github.com/distributev/mailmerger/issues/12 please give me a screenshot how to run the server from _Eclipse - **Run Configuration**_ which will consider the relative path folders which will get the command running.

Please show me a screenshot how to run with the currently eclipse configuration / relative folders

Here is the help.md documentation ==> how this should be adapted to get it working in Eclipse with relative folder paths? 

You can then run org.distributev.mailmerger.server.Application with the following program arguments

--project.dir=/full/path/to/folder/containing/watch/build.gradle
--watch.dir=/full/path/to/folder/to/watch/for/data/files
--completed.dir=/full/path/to/folder/where/data/files/will/be/placed/when/completed
--config.file=/full/path/to/mailmerger/config/file

**Comment by p-bye** [comment]
This is my configuration...

![run_configurations](https://user-images.githubusercontent.com/38662460/39621541-0b0f4a80-4f87-11e8-9338-7703610313db.png)

These parameters are passed directly to the Gradle build via the application.

You can run the equivalent  Gradle build manually within the watch folder using something like....

```
gradle --continuous mailMerger \                                                                                        master ◼
-PwatchDir=/Users/paul/jambray/upwork/client/mailmerger/test/watch \
-PmmJar=/Users/paul/jambray/upwork/client/mailmerger/mailmerger-cmdline-0.0.1-SNAPSHOT-all.jar \
-PcompletedDir=/Users/paul/jambray/upwork/client/mailmerger/test/complete \
-PconfigFile=/Users/paul/jambray/upwork/client/mailmerger/watch/default-configuration.xml
```

The `mailmerger-cmdline-0.0.1-SNAPSHOT-all.jar` was copied to the location I used for convenience.  This file contains the mailmerger-cmdline code and all dependencies bundled into a single jar file.  It can be built using `gradle shadowJar` and then found in the `mailmerger/mailmerger-cmdline/build/libs` folder.

**Comment by distributev** [comment]
Can you send the same but only with relative paths to the project folder? (instead of hard-codings like /users/paul)

**Comment by p-bye** [comment]
Try
```
--project.dir=.
--watch.dir=../test/watch
--completed.dir=../test/complete
--config.file=default-configuration.xml
--mmJar=../mailmerger-cmdline-0.0.1-SNAPSHOT-all.jar
```

I have a folder named `test` within my root `mailmerger` project which contains `watch` and `complete` folders.  These folders are not pushed to Github.
