### ISSUE TITLE
Can I use @grab inside .gradle scripts?

### ISSUE THREAD

**Issue by distributev** [distributev/mailmerger#6]
Can I do this inside the gradle scripts? This is a built-in groovy feature, gradle is groovy so I would expect that this is possible. Can you please test?

http://docs.groovy-lang.org/latest/html/documentation/grape.html

**Comment by p-bye** [comment]
I don't think so, or at least I can't get it to work.

I've tried it and it won't build due to not liking the `@Grab` annotation.  I can't find any examples online of where someone else has done this.

**Comment by distributev** [comment]
Are gradle scripts groovy scripts? If yes, @grab annotation ships out of the box / built-in into groovy ==> should work on gradle also.

Isn't it like this?

**Comment by p-bye** [comment]
I'm sorry, I'm not sure.  The closest thing I can find is https://discuss.gradle.org/t/groovy-grab-syntax-equivalent-for-gradle/6598 which suggests defining dependencies using the buildScript section of the build file.

**Comment by distributev** [comment]
OK - this is also a good answer. I thought myself to this possibility but @grab annotation would be more cleaner for general purpose scripting / automation which has nothing to do with builds.
